In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import scipy.stats as stats

C:\Users\RAHUL CHHIKARA\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
data1=pd.read_csv("dietstudy.csv")

In [3]:
data1.shape

(16, 13)

In [4]:
data1

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0       1   45    Male  180  148  106  113  100   198   196   193   188   192
1       2   56    Male  139   94  119   75   92   237   233   232   228   225
2       3   50    Male  152  185   86  149  118   233   231   229   228   226
3       4   46  Female  112  145  136  149   82   179   181   177   174   172
4       5   64    Male  156  104  157   79   97   219   217   215   213   214
5       6   49  Female  167  138   88  107  171   169   166   165   162   161
6       7   63    Male  138  132  146  143  132   222   219   215   215   210
7       8   63  Female  160  128  150  118  123   167   167   166   162   161
8       9   52    Male  107  120  129  195  174   199   200   196   196   193
9      10   45    Male  156  103  126  135   92   233   229   229   229   226
10     11   61  Female   94  144  114  114  121   179   181   176   173   173
11     12   49  Female  107   93  156  148  150   158   153   155   155   154
12     13   61  Female  145  107  129   86  159   157   151   150   145   143
13     14   59    Male  186  142  128  122  101   216   213   210   210   206
14     15   52    Male  112  107  103   89  148   257   255   254   252   249
15     16   60  Female  104  103  117   79  130   151   146   144   144   140

In [23]:
stats.ttest_rel(a = data1.tg0, b = data1.tg4)

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)

In [28]:
# Ho:Triglyceride levels not changed.

# Ha:Triglyceride levels changed.

# CI=95%

p_value=0.05

if stats.ttest_rel(a = data1.tg0, b = data1.tg4)[1]<p_value:
    print("Triglyceride levels changed(95% confident).")
else:
    print("Triglyceride levels not changed(95% confident).")

Triglyceride levels not changed(95% confident).


In [29]:
# Ho:Triglyceride levels not changed.

# Ha:Triglyceride levels changed.

# CI=99%

p_value=0.01

if stats.ttest_rel(a = data1.tg0, b = data1.tg4)[1]<p_value:
    print("Triglyceride levels changed(99% confident).")
else:
    print("Triglyceride levels not changed(99% confident).")

Triglyceride levels not changed(99% confident).


In [24]:
stats.ttest_rel(a = data1.wgt0, b = data1.wgt4)

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)

In [34]:
# Ho:Weight not changed.

# Ha:Weight changed.

# CI=95%

p_value=0.05

if stats.ttest_rel(a = data1.wgt0, b = data1.wgt4)[1]<p_value:
    print("Weight changed(95% confident).")
else:
    print("Weight not changed(95% confident).")

Weight changed(95% confident).


In [33]:
# Ho:Weight not changed.

# Ha:Weight changed.

# CI=99%

p_value=0.01

if stats.ttest_rel(a = data1.wgt0, b = data1.wgt4)[1]<p_value:
    print("Weight changed(99% confident).")
else:
    print("Weight not changed(99% confident).")

Weight changed(99% confident).


#### Conclude: There is significant amount of change in weights but there is no effect on triglyceride levels due to new diet plan.

In [5]:
data2=pd.read_csv("creditpromo.csv")

In [6]:
data2.shape

(500, 3)

In [7]:
data2.head()

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [8]:
data2['insert'].value_counts()

New Promotion    250
Standard         250
Name: insert, dtype: int64

In [9]:
s1=data2.dollars[data2['insert']=='Standard']
s2=data2.dollars[data2['insert']=='New Promotion']

In [10]:
stats.ttest_ind(a = s1, b = s2)

Ttest_indResult(statistic=-2.2604227264649963, pvalue=0.024225996894147814)

In [11]:
# Ho:The promotion is not effective in increasing sales.

# Ha:The promotion is effective in increasing sales.

# CI=95%

p_value=0.05

if stats.ttest_ind(a = s1, b = s2)[1]<p_value: #Using two sample ttest(independent)
    print("The promotion is effective in increasing sales(95% confident).")
else:
    print("The promotion is not effective in increasing sales(95% confident).")

The promotion is effective in increasing sales(95% confident).


In [12]:
# Ho:The promotion is not effective in increasing sales.

# Ha:The promotion is effective in increasing sales.

# CI=99%

p_value=0.01

if stats.ttest_ind(a = s1, b = s2)[1]<p_value: #Using two sample ttest(independent)
    print("The promotion is effective in increasing sales(99% confident).")
else:
    print("The promotion is not effective in increasing sales(99% confident).")

The promotion is not effective in increasing sales(99% confident).


#### Conclude: Promotion is effective in increasing sales and we can say that with 95% confident.

In [ ]:
data3=pd.read_csv("pollination.csv")

In [12]:
data3.shape

(20, 4)

In [124]:
data3.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [87]:
stats.ttest_1samp(a=data3.Seed_Yield_Plant,popmean=200)

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

In [86]:
# Ho: mu!=200

# Ha: mu=200

# CI=95%

p_value=0.05

if (stats.ttest_1samp(a=data3.Seed_Yield_Plant,popmean=200)[1] < p_value): #If stats value less than p, we will reject the null hypothesis.
    print("Overall population of Seed yield/plant(g) equals to 200.")
else:
    print("Overall population of Seed yield/plant(g) not equals to 200.")

Overall population of Seed yield/plant(g) equals to 200.


In [88]:
data3.Group.value_counts()

Hand       10
Natural    10
Name: Group, dtype: int64

In [92]:
s1=data3[data3['Group']=='Hand']
s2=data3[data3['Group']=='Natural']

In [95]:
# Ho:Equally effective.

# Ha:Significantly different.

# CI=99%

p_value=0.01

if stats.ttest_ind(a = s1.Fruit_Wt, b = s2.Fruit_Wt)[1]<p_value:  #Comparing food weight.
    print("Significantly different.")
else:
    print("Equally effective.")

Significantly different.


In [96]:
# Ho:Equally effective.

# Ha:Significantly different.

# CI=99%

p_value=0.01

if stats.ttest_ind(a = s1.Seed_Yield_Plant, b = s2.Seed_Yield_Plant)[1]<p_value:  #Comparing seed yield plant.
    print("Significantly different.")
else:
    print("Equally effective.")

Significantly different.


In [98]:
# Ho:Equally effective.

# Ha:Significantly different.

# CI=99%

p_value=0.01

if stats.ttest_ind(a = s1.Seedling_length, b = s2.Seedling_length)[1]<p_value:  #Comparing food weight.
    print("Significantly different.")
else:
    print("Equally effective.")

Equally effective.


In [99]:
stats.ttest_ind(a = s1.Seedling_length, b = s2.Seedling_length)

Ttest_indResult(statistic=2.542229999657055, pvalue=0.020428817064110226)

#### Conclude: Hand pollitnation is more effective than natural pollination but not have a major change in seed length.

In [15]:
data4=pd.read_csv("dvdplayer.csv")

In [17]:
data4.shape

(68, 2)

In [115]:
data4.head()

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

In [100]:
data4.agegroup.value_counts()

65 and over    17
Under 25       13
35-44          12
45-54          10
25-34          10
55-64           6
Name: agegroup, dtype: int64

In [119]:
s1=data4.dvdscore[data4['agegroup']=='65 and over']
s2=data4.dvdscore[data4['agegroup']=='Under 25']
s3=data4.dvdscore[data4['agegroup']=='35-44']
s4=data4.dvdscore[data4['agegroup']=='45-54']
s5=data4.dvdscore[data4['agegroup']=='25-34']
s6=data4.dvdscore[data4['agegroup']=='55-64']

In [121]:
stats.f_oneway(s1,s2,s3,s4,s5,s6)

F_onewayResult(statistic=6.992526962676517, pvalue=3.087324905679639e-05)

In [123]:
# Ho:Consumers of various ages rated the design similarly.

# Ha:Consumers of various ages rated the design differently.

# CI=99%

p_value=0.01

if stats.f_oneway(s1,s2,s3,s4,s5,s6)[1]<p_value:   #Using ANOVA as we are comparing the different categories.
    print("Consumers of various ages rated the design differently.")
else:
    print("Consumers of various ages rated the design similarly.")

Consumers of various ages rated the design differently.


#### Conclude: Consumers of various ages rated the design differently.

In [13]:
data5=pd.read_csv("sample_survey.csv")

In [14]:
data5.shape

(2832, 46)

In [15]:
data5.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree  ...        agecat childcat news1 news2  news3  \
0     NaN     High school  ...      55 to 64      1-2    No    No     No   
1     NaN  Junior college  ...      25 to 34     None    No    No    Yes   
2    16.0     High school  ...      35 to 44      1-2    No    No     No   
3     NaN     High school  ...  Less than 25     None    No    No     No   
4     NaN        Bachelor  ...      35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [16]:
s=data5.groupby(["wrkstat","marital"]).id.count().reset_index()
t=s.pivot("wrkstat","marital","id")
t.dropna(axis=0)

marital                  Divorced  Married  Never married  Separated  Widowed
wrkstat                                                                      
Keeping house                25.0    200.0           35.0       13.0     55.0
Other                        12.0     16.0           14.0        4.0      8.0
Retired                      53.0    168.0           17.0        6.0    150.0
School                        7.0      9.0           60.0        2.0      1.0
Temporarily not working       9.0     23.0           11.0        1.0      2.0
Working full time           295.0    778.0          392.0       58.0     44.0
Working part-time            35.0    138.0          102.0        9.0     20.0

In [17]:
t=data5.pivot_table(index='wrkstat',columns='marital',values='id',aggfunc='count') #Observed frequency table using  pivot only.
t.dropna(axis=0)

marital                  Divorced  Married  Never married  Separated  Widowed
wrkstat                                                                      
Keeping house                25.0    200.0           35.0       13.0     55.0
Other                        12.0     16.0           14.0        4.0      8.0
Retired                      53.0    168.0           17.0        6.0    150.0
School                        7.0      9.0           60.0        2.0      1.0
Temporarily not working       9.0     23.0           11.0        1.0      2.0
Working full time           295.0    778.0          392.0       58.0     44.0
Working part-time            35.0    138.0          102.0        9.0     20.0

In [19]:
t=pd.crosstab(index=data5.wrkstat,columns=data5.marital,margins=False) #Observed frequency using crosstab
t       # This method is preferred as its default aggregate function is count.

marital                  Divorced  Married  Never married  Separated  Widowed
wrkstat                                                                      
Keeping house                  25      200             35         13       55
Other                          12       16             14          4        8
Retired                        53      168             17          6      150
School                          7        9             60          2        1
Temporarily not working         9       23             11          1        2
Unemployed, laid off           10       13             32          0        3
Working full time             295      778            392         58       44
Working part-time              35      138            102          9       20

In [20]:
stats.chi2_contingency(observed=t)

(729.2421426572284,
 1.4875268409067568e-135,
 28,
 array([[ 51.69187279, 155.8869258 ,  76.84240283,  10.77879859,
          32.8       ],
        [  8.51024735,  25.66431095,  12.65088339,   1.7745583 ,
           5.4       ],
        [ 62.09328622, 187.25441696,  92.30459364,  12.94770318,
          39.4       ],
        [ 12.45017668,  37.5459364 ,  18.50777385,   2.59611307,
           7.9       ],
        [  7.24946996,  21.86219081,  10.77667845,   1.51166078,
           4.6       ],
        [  9.14063604,  27.56537102,  13.58798587,   1.90600707,
           5.8       ],
        [246.95477032, 744.74028269, 367.10989399,  51.495053  ,
         156.7       ],
        [ 47.90954064, 144.48056537,  71.21978799,   9.99010601,
          30.4       ]]))

In [21]:
# Ho = Both labour force status and marital status are independant variables.

# Ha = Both labour force status and marital status are dependant variables.

# CI = 99%

p = 0.01

if stats.chi2_contingency(t)[1] < p:
    print('Both labour force status and marital status are dependant variables.')
else:
    print('Both labour force status and marital status are independant variables.')

Both labour force status and marital status are dependant variables.


In [22]:
t=pd.crosstab(index=data5.marital,columns=data5.degree,margins=False) #Observed frequency using crosstab
t       # This method is preferred as its default aggregate function is count.

degree         Bachelor  Graduate  High school  Junior college  LT High school
marital                                                                       
Divorced             58        29          241              45              70
Married             251       123          686             108             174
Never married       129        41          367              46              77
Separated            12         3           58               3              17
Widowed              28         9          148               6              92

In [23]:
stats.chi2_contingency(t)

(122.68449020508541,
 1.6707923432360119e-18,
 16,
 array([[ 75.06345268,  32.19248493, 235.55476781,  32.66359447,
          67.52570011],
        [227.39312301,  97.52215526, 713.57674583,  98.94930876,
         204.55866714],
        [111.83268345,  47.9617157 , 350.9393832 ,  48.66359447,
         100.60262318],
        [ 15.75824176,   6.75824176,  49.45054945,   6.85714286,
          14.17582418],
        [ 47.95249911,  20.56540234, 150.4785537 ,  20.86635945,
          43.1371854 ]]))

In [24]:
# Ho = Both educational qualification and marital status are independant variables.

# Ha = Both educational qualification and marital status are dependant variables.

# CI = 99%

p = 0.01

if stats.chi2_contingency(t)[1] < p:
    print('Both educational qualification and marital status are dependant variables.')
else:
    print('Both educational qualification and marital status are independant variables.')

Both educational qualification and marital status are dependant variables.


In [199]:
t=pd.crosstab(index=data5.happy,columns=data5.income,margins=False) #Observed frequency using crosstab
t       # This method is preferred as its default aggregate function is count.

income         $1000 TO 2999  $10000 - 14999  $15000 - 19999  $20000 - 24999  \
happy                                                                          
Not too happy              7              39              33              40   
Pretty happy              20             107             119             155   
Very happy                 5              44              26              50   

income         $25000 or more  $3000 TO 3999  $4000 TO 4999  $5000 TO 5999  \
happy                                                                        
Not too happy             113              9              9              6   
Pretty happy              888             11             13             18   
Very happy                571              4             10             11   

income         $6000 TO 6999  $7000 TO 7999  $8000 TO 9999  LT $1000  
happy                                                                 
Not too happy             14             12              9        11  
Pretty happy              13             21             30        13  
Very happy                 6             14             19        11

In [200]:
stats.chi2_contingency(t)

(178.9505306121643,
 1.4107677273473057e-26,
 22,
 array([[  3.89520355,  23.12777106,  21.66706973,  29.82265216,
         191.35187424,   2.92140266,   3.89520355,   4.26037888,
           4.01692866,   5.72108021,   7.06005643,   4.26037888],
        [ 18.16041919, 107.82748892, 101.01733172, 139.04070939,
         892.1305925 ,  13.62031439,  18.16041919,  19.86295848,
          18.72793229,  26.67311568,  32.91575977,  19.86295848],
        [  9.94437727,  59.04474002,  55.31559855,  76.13663845,
         488.51753325,   7.45828295,   9.94437727,  10.87666264,
          10.25513906,  14.60580411,  18.0241838 ,  10.87666264]]))

In [202]:
# Ho = Happiness is not driven by income.

# Ha = Happiness is driven by income.

# CI = 99%

p = 0.01

if stats.chi2_contingency(t)[1] < p:
    print('Happiness is driven by income.')
else:
    print('Happiness is not driven by income.')

Happiness is driven by income.


In [203]:
t=pd.crosstab(index=data5.happy,columns=data5.marital,margins=False) #Observed frequency using crosstab
t       # This method is preferred as its default aggregate function is count.

marital        Divorced  Married  Never married  Separated  Widowed
happy                                                              
Not too happy        72       71            108         30       59
Pretty happy        278      684            426         49      137
Very happy           93      582            120         13       83

In [204]:
stats.chi2_contingency(t)

(260.6894389418282,
 9.3147261197964e-52,
 8,
 array([[ 53.6969697 , 162.06060606,  79.27272727,  11.15151515,
          33.81818182],
        [248.58538324, 750.24527629, 366.98609626,  51.62495544,
         156.55828877],
        [140.71764706, 424.69411765, 207.74117647,  29.22352941,
          88.62352941]]))

In [205]:
# Ho = Happiness is not driven by marital.

# Ha = Happiness is driven by marital.

# CI = 99%

p = 0.01

if stats.chi2_contingency(t)[1] < p:
    print('Happiness is driven by marital.')
else:
    print('Happiness is not driven by marital.')

Happiness is driven by marital.


#### Conclude: Happiness is driven by both income and marital status